package de.tum.cit.ase.maze;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Screen;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.scenes.scene2d.Actor;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton;
import com.badlogic.gdx.scenes.scene2d.utils.ChangeListener;
import com.badlogic.gdx.utils.Scaling;
import com.badlogic.gdx.utils.viewport.FillViewport;
import com.badlogic.gdx.utils.viewport.ScreenViewport;
import com.badlogic.gdx.utils.viewport.Viewport;
import games.spooky.gdx.nativefilechooser.NativeFileChooserCallback;
import games.spooky.gdx.nativefilechooser.NativeFileChooserConfiguration;

public class GameOverScreen implements Screen {

    private MazeRunnerGame game;
    private OrthographicCamera camera;
    private Viewport viewport;
    private final Stage stage;
    private Texture backgroundTexture;

    /**
     * Constructs a GameOverScreen for the MazeRunnerGame.
     * <p>
     * This constructor initializes the GameOverScreen with a reference to the MazeRunnerGame instance.
     * It sets up the camera and viewport to define how the game's UI is projected onto the screen.
     * A new stage is created with the specified viewport and the game's batch for drawing.
     * Additionally, the constructor calls methods to add a background image and interactive buttons
     * to the menu screen. This setup ensures that the pause screen is ready to display when the player pressed 'Esc'.
     * </p>
     *
     * @param game The MazeRunnerGame instance this menu screen is a part of. This is used to access
     *             game-wide properties and functionalities.
     *
     * @see MazeRunnerGame
     * @see OrthographicCamera
     * @see FillViewport
     * @see Stage
     */
    public GameOverScreen(MazeRunnerGame game) {
        this.game = game;
        camera = new OrthographicCamera();
        viewport = new FillViewport(Gdx.graphics.getWidth() * 1.5f, Gdx.graphics.getHeight() * 1.5f, camera);
        stage = new Stage(viewport, game.getBatch());

        // add background image
        addBackgroundImage();

        // add buttons
        addButtons();
    }

    /**
     * Renders the game over screen.
     * <p>
     * This method is an override of the render function used to draw the game over screen.
     * It primarily deals with rendering UI elements like buttons. The method clears the screen
     * and then updates and draws the stage, which contains the UI elements. The {@code stage.act}
     * method is called with a delta time, which updates the state of the UI elements.
     * Following this, {@code stage.draw} is used to render the UI elements on the screen.
     * This method ensures that the game over screen is appropriately updated and drawn at each frame refresh.
     * </p>
     *
     * @param delta The time span between the current and last frame in seconds, used for updating
     *              the stage's act method.
     */
    @Override
    public void render(float delta) {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        stage.act(Math.min(Gdx.graphics.getDeltaTime(), 1/ 30f));
        stage.draw();
    }

    /**
     * Adds a background image to the game over screen.
     * <p>
     * This method loads and sets a background image for the game over screen. The image is obtained
     * from the assets folder ("game_over_screen_background.png"). The image is set to fill
     * the entire screen, ensuring that it covers the game over screen's full area.
     * </p>
     */
    private void addBackgroundImage() {
        backgroundTexture = new Texture(Gdx.files.internal("game_over_screen_background.png"));      // the image is generated by an AI
        Image background = new Image(backgroundTexture);
        background.setName("background");
        background.setFillParent(true);
        background.setScaling(Scaling.fill);
        stage.addActor(background);
    }

    /**
     * Adds interactive buttons to the game over screen.
     * <p>
     * This method sets up and adds UI elements, particularly buttons, to the game over screen.
     * The buttons include:
     * <ul>
     *     <li>'Play Again' button: Allows the player to play the same level again.</li>
     *     <li>'Choose Different Map' button: Allows the player to choose a map file and start the game in initial state.</li>
     *     <li>'Go to Main Menu' button: Allows the player to go back to the menu screen.</li>
     * </ul>
     * The method also adds a welcome label to the screen. The buttons and label are organized
     * within a table layout for consistent and manageable positioning. Listeners are attached
     * to the buttons to handle the respective actions when they are clicked.
     * </p>
     *
     * @see NativeFileChooserConfiguration
     * @see NativeFileChooserCallback
     */
    private void addButtons() {
        // add buttons
        Table table = new Table();
        table.setFillParent(true);
        stage.addActor(table);

        // add a label
        table.add(new Label("Game Over!", game.getSkin(), "title")).padBottom(80).row();

        table.defaults().padBottom(10);
        // create and add Play Again Button
        TextButton playAgainButton = new TextButton("Play Again", game.getSkin());
        table.add(playAgainButton).width(400).row();
        playAgainButton.addListener(new ChangeListener() {
            @Override
            public void changed(ChangeEvent event, Actor actor) {
                game.goToGame();
            }
        });

        // create and add Choose New Map Button
        TextButton chooseNewMapButton = new TextButton("Choose Different Map", game.getSkin());
        table.add(chooseNewMapButton).width(400).row();
        chooseNewMapButton.addListener(new ChangeListener() {
            @Override
            public void changed(ChangeEvent event, Actor actor) {
                NativeFileChooserConfiguration conf = FileChooserHelper.mapChooserConfiguration();
                game.getFileChooser().chooseFile(conf, new NativeFileChooserCallback() {
                    @Override
                    public void onFileChosen(FileHandle file) {
                        game.setFileHandle(file);
                        game.goToGame();
                    }

                    @Override
                    public void onCancellation() {

                    }

                    @Override
                    public void onError(Exception exception) {

                    }
                });
            }
        });

        // create and add Back To Menu Button
        TextButton backToMenuButton = new TextButton("Back to Main Menu", game.getSkin());
        table.add(backToMenuButton).width(400).row();
        backToMenuButton.addListener(new ChangeListener() {
            @Override
            public void changed(ChangeEvent event, Actor actor) {
                game.gotoMenu();
            }
        });
    }

    @Override
    public void show() {
        Gdx.input.setInputProcessor(stage);
    }

    @Override
    public void resize(int width, int height) {
        stage.getViewport().update(width, height, true);
        Image background = (Image) stage.getRoot().findActor("background");
        if (background != null) {
            background.setSize(stage.getWidth(), stage.getHeight());
        }
    }

    @Override
    public void pause() {

    }

    @Override
    public void resume() {

    }

    @Override
    public void hide() {

    }

    @Override
    public void dispose() {

    }
}

