package de.tum.cit.ase.maze.screens;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Screen;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.scenes.scene2d.Actor;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton;
import com.badlogic.gdx.scenes.scene2d.utils.ChangeListener;
import com.badlogic.gdx.utils.Scaling;
import com.badlogic.gdx.utils.viewport.FillViewport;
import com.badlogic.gdx.utils.viewport.Viewport;
import de.tum.cit.ase.maze.MazeRunnerGame;
import de.tum.cit.ase.maze.helpers.FileChooserHelper;
import games.spooky.gdx.nativefilechooser.NativeFileChooserCallback;
import games.spooky.gdx.nativefilechooser.NativeFileChooserConfiguration;

public class MenuScreen implements Screen {

    private MazeRunnerGame game;
    private OrthographicCamera camera;
    private Viewport viewport;
    private final Stage stage;
    private Texture backgroundTexture;

    /**
     * Constructs a MenuScreen for the MazeRunnerGame.
     * <p>
     * This constructor initializes the MenuScreen with a reference to the MazeRunnerGame instance.
     * It sets up the camera and viewport to define how the game's UI is projected onto the screen.
     * A new stage is created with the specified viewport and the game's batch for drawing.
     * Additionally, the constructor calls methods to add a background image and interactive buttons
     * to the menu screen. This setup ensures that the menu screen is ready to display with all
     * necessary UI elements when the game starts or when the menu is accessed.
     * </p>
     *
     * @param game The MazeRunnerGame instance this menu screen is a part of. This is used to access
     *             game-wide properties and functionalities.
     *
     * @see MazeRunnerGame
     * @see OrthographicCamera
     * @see FillViewport
     * @see Stage
     */
    public MenuScreen(MazeRunnerGame game) {
        this.game = game;
        camera = new OrthographicCamera();
        viewport = new FillViewport(Gdx.graphics.getWidth() * 1.5f, Gdx.graphics.getHeight() * 1.5f, camera);
        stage = new Stage(viewport, game.getBatch());

        // add background image
        addBackgroundImage();

        // add buttons
        addButtons();
    }

    /**
     * Renders the menu screen.
     * <p>
     * This method is an override of the render function used to draw the menu screen.
     * It primarily deals with rendering UI elements like buttons. The method clears the screen
     * and then updates and draws the stage, which contains the UI elements. The {@code stage.act}
     * method is called with a delta time (capped at a maximum to avoid large time jumps),
     * which updates the state of the UI elements. Following this, {@code stage.draw} is used
     * to render the UI elements on the screen. This method ensures that the menu screen is
     * appropriately updated and drawn at each frame refresh.
     * </p>
     *
     * @param delta The time span between the current and last frame in seconds, used for updating
     *              the stage's act method.
     */
    @Override
    public void render(float delta) {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        stage.act(Math.min(Gdx.graphics.getDeltaTime(), 1 / 30f));
        stage.draw();
    }

    /**
     * Adds a background image to the menu screen.
     * <p>
     * This method loads and sets a background image for the menu screen. The image is obtained
     * from the specified file path ("menu_screen_background.png"). The image is set to fill
     * the entire screen, ensuring that it covers the menu screen's full area.
     * </p>
     */
    private void addBackgroundImage() {
        backgroundTexture = new Texture(Gdx.files.internal("menu_screen_background.png"));      // the image is generated by an AI
        Image background = new Image(backgroundTexture);
        background.setName("background");
        background.setFillParent(true);
        background.setScaling(Scaling.fill);
        stage.addActor(background);
    }

    /**
     * Adds interactive buttons to the menu screen.
     * <p>
     * This method sets up and adds UI elements, particularly buttons, to the menu screen.
     * The buttons include:
     * <ul>
     *     <li>'Play Game' button: Allows the player to choose a map file and start the game.
     *         This button triggers a file chooser for selecting the map and then transitions
     *         the game to the gameplay screen.</li>
     *     <li>'Exit Game' button: Closes the game application.</li>
     * </ul>
     * The method also adds a welcome label to the screen. The buttons and label are organized
     * within a table layout for consistent and manageable positioning. Listeners are attached
     * to the buttons to handle the respective actions when they are clicked.
     * </p>
     *
     * @see NativeFileChooserConfiguration
     * @see NativeFileChooserCallback
     */
    private void addButtons() {
        // add a table onto stage
        Table table = new Table();
        table.setFillParent(true);
        stage.addActor(table);

        // add a welcome text(label) to table
        table.add(new Label("Welcome to the Maze Runner", game.getSkin(), "title")).padBottom(80).row();

        // set default padding for buttons
        table.defaults().padBottom(20);

        // Create and add buttons to enter the game interface
        TextButton goToGameButton = new TextButton("Play Game", game.getSkin());
        table.add(goToGameButton).width(300).row();
        goToGameButton.addListener(new ChangeListener() {
            @Override
            public void changed(ChangeEvent event, Actor actor) {
                NativeFileChooserConfiguration conf = FileChooserHelper.mapChooserConfiguration();
                game.getFileChooser().chooseFile(conf, new NativeFileChooserCallback() {
                    @Override
                    public void onFileChosen(FileHandle file) {
                        game.setFileHandle(file);
                        game.goToGame();
                    }

                    @Override
                    public void onCancellation() {

                    }

                    @Override
                    public void onError(Exception exception) {
                        System.out.println(exception);
                    }
                });
            }
        });

        // Create and add a button to exit the game
        TextButton exitButton = new TextButton("Exit Game", game.getSkin());
        table.add(exitButton).width(300).row();
        exitButton.addListener(new ChangeListener() {
            @Override
            public void changed(ChangeEvent event, Actor actor) {
                Gdx.app.exit();
            }
        });
    }

    /**
     * Sets up the input processor when the screen is shown.
     * <p>
     * This method is called when this screen becomes the current screen for a {@link MazeRunnerGame}.
     * It sets the input processor to the stage, enabling the screen to receive and handle
     * user input events through the stage's actors.
     * </p>
     */
    @Override
    public void show() {
        Gdx.input.setInputProcessor(stage);
    }

    /**
     * Updates the viewport of the stage when the screen size changes.
     * <p>
     * This method is called when the screen size is changed. It adjusts the viewport of
     * the stage to match the new screen dimensions, ensuring that UI elements are scaled
     * and positioned correctly according to the new size.
     * </p>
     *
     * @param width The new width of the screen.
     * @param height The new height of the screen.
     */
    @Override
    public void resize(int width, int height) {
        stage.getViewport().update(width, height, true);
    }

    @Override
    public void pause() {

    }

    @Override
    public void resume() {

    }

    @Override
    public void hide() {

    }

    public Stage getStage() {
        return stage;
    }

    public MazeRunnerGame getGame() {
        return game;
    }

    public void setGame(MazeRunnerGame game) {
        this.game = game;
    }

    public OrthographicCamera getCamera() {
        return camera;
    }

    public void setCamera(OrthographicCamera camera) {
        this.camera = camera;
    }

    public Viewport getViewport() {
        return viewport;
    }

    public void setViewport(Viewport viewport) {
        this.viewport = viewport;
    }

    public Texture getBackgroundTexture() {
        return backgroundTexture;
    }

    public void setBackgroundTexture(Texture backgroundTexture) {
        this.backgroundTexture = backgroundTexture;
    }

    /**
     * Disposes of the resources used by the MenuScreen.
     * <p>
     * This method is called when the MenuScreen is no longer needed and is being removed from memory.
     * It ensures that the resources, particularly the stage and the background texture, are properly
     * disposed of. This is important for preventing memory leaks by freeing up the resources that
     * are no longer in use. The method overrides the dispose method of the parent class.
     * </p>
     */
    @Override
    public void dispose() {
        stage.dispose();
        backgroundTexture.dispose();
    }
}
